Controllers/GradesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VDiary.Data;
using VDiary.Models;
using VDiary.Models.Dtos;

namespace VDiary.Controllers
{
    [Authorize]
    public class GradesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GradesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Grades/IndexForLecturer/1
        public async Task<IActionResult> IndexForLecturer(int? pageNumber)
        {
            var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var pageSize = 5;

            var applicationDbContext = await _context.SubjectUser
                    .Where(g => g.BelongsTo == userId )
                .Select(su => su.Subject)
                .Distinct()
                .ToListAsync()
                ;
            ViewData["lecturerId"] = userId;
            ;
            var grades = new PaginatedList<Subject>(applicationDbContext, applicationDbContext.Count, pageNumber ?? 1, pageSize);
            ViewData["HasPreviousPage"] = grades.HasPreviousPage;
            ViewData["HasNextPage"] = grades.HasNextPage;
            ViewData["PageIndex"] = grades.PageIndex;
            return View(await PaginatedList<Subject>.Create(grades, pageNumber ?? 1, pageSize));
        }
        // GET: Grades/IndexForStudent/1
        [Authorize(Roles = "Student")]
        public async Task<IActionResult> IndexForStudent(int? pageNumber)
        {
            var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            ViewData["userFullName"] = User.FindFirstValue(ClaimTypes.Name);


            var pageSize = 5;

            var applicationDbContext = _context.Grade
                .Include(m => m.Subject)
                .Include(m => m.User)
                .Where( m => m.UserId == userId )
                .Distinct()
                .AsEnumerable()
                .ToList()
                ;

            ViewData["Subjects"] = await _context.SubjectUser
                .Include(su => su.User)
                .Include(su => su.Subject)
                .Where(su => su.UserId == userId)
                .Distinct()
                .Select(su => su.Subject)
                .ToListAsync();

            var grades = new PaginatedList<Grade>(applicationDbContext, applicationDbContext.Count, pageNumber ?? 1, pageSize);
            ViewData["HasPreviousPage"] = grades.HasPreviousPage;
            ViewData["HasNextPage"] = grades.HasNextPage;
            ViewData["PageIndex"] = grades.PageIndex;
            return View(await PaginatedList<Grade>.Create(grades, pageNumber ?? 1, pageSize));
        }

        public async Task<IActionResult> AllGradesOfStudent(int studentId,int subjectId)
        {

            if (studentId == 0 || studentId == null)
            {
                return NotFound();
            }

            var results = await _context.Grade
                .Include(g => g.User)
                .Where(g => g.UserId == studentId)
                .Where(g => g.SubjectId == subjectId)
                .ToListAsync();
            
            ViewData["UserName"] = _context.User.SingleOrDefault( u => u.Id == studentId);
            ViewData["SubjectId"] = subjectId;


            return View(results);
        }

        // GET: Marks/Create
        [Authorize(Roles = "Lecturer")]
        public IActionResult CreateDefault()
        {

            var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var subjects =  _context.Course
                .Where(c => c.LecturerId == userId)
                .Select(c => c.Subject)
                ;

            var students = _context.SubjectUser
                .Where(su => su.BelongsTo == userId)
                .Where(su => su.User.Role.Name == "Student")
                .Select(su => su.User);

            ViewData["SubjectId"] = new SelectList(subjects, "Id", "Name");
            ViewData["UserId"] = new SelectList(students, "Id", "FullName");
            return View();
        }
        // GET: Marks/Create/1
        [Authorize(Roles = "Lecturer")]
        public IActionResult Create(int? id)// subjectID,
        {
            if (id is null)
            {
                return RedirectToAction("CreateDefault");
            }
            var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var subject =  _context.Subject
                .FirstOrDefault(s => s.Id == id );

            var students = _context.SubjectUser
                .Where(su => su.BelongsTo == userId)
                .Where(su => su.User.Role.Name == "Student")
                .Where(s => s.Subject ==  subject)
                .Select(su => su.User);

            ViewData["SubjectId"] = subject.Id;
            ViewData["UserId"] = new SelectList(students, "Id", "FullName");
            return View();
        }

        // POST: Marks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Lecturer")]
        public async Task<IActionResult> Create([Bind("GradeMark,Date,Description,UserId,SubjectId,CreatedBy")] Grade grade)
        {
            var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            grade.CreatedBy = userId;
            if (ModelState.IsValid)
            {
                _context.Add(grade);
                await _context.SaveChangesAsync();
                return RedirectToAction("AllGradeForSubject",new{ id = grade.SubjectId});
            }
            ViewData["SubjectId"] = new SelectList(_context.Subject, "Id", "Name", grade.SubjectId);
            ViewData["UserId"] = new SelectList(_context.User, "Id", "AlbumNumber", grade.UserId);
            return View(grade);
        }

        // GET: Marks/Edit/5
        [Authorize(Roles = "Lecturer")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mark = await _context.Grade.FindAsync(id);
            if (mark == null)
            {
                return NotFound();
            }
            ViewData["SubjectId"] = new SelectList(_context.Subject, "Id", "Name", mark.SubjectId);
            ViewData["UserId"] = new SelectList(_context.User, "Id", "AlbumNumber", mark.UserId);
            return View(mark);
        }

        // POST: Marks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Lecturer")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,GradeMark,Date,Description,UserId,SubjectId,CreatedBy")] Grade grade)
        {
            if (id != grade.Id)
            {
                return NotFound();
            }

            var subjectId = grade.SubjectId;
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(grade);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Grade.Any(e => e.Id == grade.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(AllGradeForSubject), new { id = subjectId });
            }
            ViewData["SubjectId"] = new SelectList(_context.Subject, "Id", "Name", grade.SubjectId);
            ViewData["UserId"] = new SelectList(_context.User, "Id", "AlbumNumber", grade.UserId);
            return View();
        }

        // GET: Marks/Delete/5
        [Authorize(Roles = "Lecturer")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mark = await _context.Grade
                .Include(m => m.Subject)
                .Include(m => m.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mark == null)
            {
                return NotFound();
            }

            return View(mark);
        }

        // POST: Marks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mark = await _context.Grade.FindAsync(id);
            _context.Grade.Remove(mark);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(IndexForLecturer));
        }

        public async Task<IActionResult> AllGradeForSubject(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }
            var lecturerId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var subject = _context.Subject.FirstOrDefault(s => s.Id == id);
            var grades = await _context.Grade
                .Include(g => g.Subject)
                .Include(g => g.User)
                .Where(g => g.SubjectId == id)
                .Where(g => g.CreatedBy == lecturerId)
                .ToListAsync();

            ViewData["Subject"] = subject;

            ViewData["Students"]= await _context.User

Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VDiary.Data;
using VDiary.Models;

namespace VDiary.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RolesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Roles
        
        public async Task<IActionResult> Index()
        {
            return View(await _context.Role.ToListAsync());
        }

        // GET: Roles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name")] Role role)
        {
            if (ModelState.IsValid)
            {
                _context.Add(role);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Roles/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Role
                .AsNoTracking()
                .FirstOrDefaultAsync(r => r.Id == id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            var roleToUpdate = await _context.Role.FirstOrDefaultAsync(r => r.Id == id);
            if (await TryUpdateModelAsync<Role>(roleToUpdate, 
                "",
                r => r.Name
                ))
            {
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Role.Any(e => e.Id == roleToUpdate.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(roleToUpdate);
        }

        // GET: Roles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await _context.Role
                .FirstOrDefaultAsync(m => m.Id == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var role = await _context.Role.FindAsync(id);
            _context.Role.Remove(role);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

Views/Shared/_Layout.cshtml
@using System.Security.Claims
@{
    var userId="";
    var userRole = "";
    @if (User.Identity.IsAuthenticated)
    {
        userId = @User.FindFirst(c => c.Type == ClaimTypes.NameIdentifier).Value;
        userRole= @User.FindFirst(c => c.Type == ClaimTypes.Role).Value;
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VDiary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Courses" asp-action="Index" asp-route-id="@userId">VDiary</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            @if (userRole == "Admin")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                                </li>
                            }
                            @if (userRole == "Admin")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Subjects" asp-action="Index">Subjects</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index" asp-route-id="@userId">Schedule</a>
                            </li>
                            @if (userRole == "Lecturer")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Grades" asp-action="IndexForLecturer">My Courses</a>
                                </li>
                            }
                            @if (userRole == "Student")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Grades" asp-action="IndexForStudent">My Grades</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Presences" asp-action="PresencesForStudent">My Presences</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Details" asp-route-id="@userId">@User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - VDiary - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>