Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using VDiary.Data;
using VDiary.Models;
using VDiary.Models.Dtos;

namespace VDiary.Controllers
{
    [Authorize]
    public class CoursesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CoursesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Courses/1
        public async Task<IActionResult> Index(int? pageNumber)
        {
            
            var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var userRole = User.FindFirstValue(ClaimTypes.Role);
            int pageSize = 5;

            if (pageNumber is null)
            {
                pageNumber = 1;
            }
            var applicationDbContext = await _context.Course
                .Include(c => c.Subject)
                .Include(c => c.Lecturer)
                .OrderBy(c => c.Time)
                .ToListAsync();
            if (userRole == "Lecturer")
            {
                applicationDbContext = applicationDbContext
                    .Where(c => c.Lecturer.Id == userId)
                    .Distinct()
                    .ToList();
            }

            if (userRole == "Student")
            {
                applicationDbContext = await _context.Presence
                    .Where(p => p.UserId == userId)
                    .Select(p => p.Course)
                    .Distinct()
                    .OrderBy(c => c.Time)
                    .ToListAsync();
            }
            var pList = new PaginatedList<Course>(applicationDbContext, applicationDbContext.Count, pageNumber ?? 1, pageSize);
            ViewData["HasPreviousPage"] = pList.HasPreviousPage;
            ViewData["HasNextPage"] = pList.HasNextPage;
            ViewData["PageIndex"] = pList.PageIndex;
            return View(await PaginatedList<Course>.Create(applicationDbContext, pageNumber ?? 1, pageSize));
        }

        // GET: Courses/Details/5
        [Authorize(Roles = "Lecturer,Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Course
                .Include(c => c.Subject)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        [Authorize(Roles = "Lecturer,Admin")]
        public IActionResult Create()
        {
            ViewData["SubjectId"] = new SelectList(_context.Subject, "Id", "Name");
            ViewData["LecturerId"] = new SelectList(_context.User.Where(u => u.RoleId == 2), "Id", "FullName");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Lecturer,Admin")]
        public async Task<IActionResult> Create([Bind("SubjectId,LecturerId,Time,Venue,GroupName")] Course course)
        {
            var relation = new SubjectUser();
            relation.SubjectId = course.Id;
            relation.UserId = course.LecturerId;
            relation.Subject = _context.Subject.Find(course.SubjectId);
            relation.User = _context.User.Find(course.LecturerId);
            relation.BelongsTo = course.LecturerId;

            if (course.Time < DateTime.Now)
            {
                course.Active = false;
            }
            else
            {
                course.Active = true;
            }


            if (ModelState.IsValid)
            {
                _context.Add(course);
                _context.SubjectUser.Add(relation);
                await _context.SaveChangesAsync();
                if (User.FindFirstValue(ClaimTypes.Role) == "Admin")
                {
                    return RedirectToAction(nameof(Index), new { id = 1});
                }
                return RedirectToAction(nameof(Index),new {id = course.LecturerId});
            }
            ViewData["SubjectId"] = new SelectList(_context.Subject, "Id", "Name");
            ViewData["LecturerId"] = new SelectList(_context.User.Where(u => u.RoleId == 2), "Id", "FullName");
            return View(course);
        }

        //GET : Courses/CreateNewDate/1
        [Authorize(Roles = "Lecturer,Admin")]
        public async Task<IActionResult> CreateNewDate(int? id) //previous course id 
        {
            if (id == null)
            {
                return NotFound();
            }
            var course = await _context.Course
                .Include(c => c.Subject)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);

        }

        // POST: Courses/CreateNewDate/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Lecturer,Admin")]
        public async Task<IActionResult> CreateNewDate(int id ,[Bind("Id,SubjectId,LecturerId,Time,Venue,GroupName,Active")] Course courseOld)
        {

            
            var newDate = courseOld.Time;
            courseOld = await _context.Course.FirstOrDefaultAsync(c => c.Id == courseOld.Id);
            if (courseOld.Time >= newDate)
            {
                TempData["Error"] = "New date have to latest than previous";
                return View(courseOld);
            }
            courseOld.Id = 0;
            var course = new Course();
            course = courseOld;
            course.Active = newDate < DateTime.Now;
            course.Time = newDate;
            
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var presences = _context.Presence.Where(p => p.CourseId == id);


            if (ModelState.IsValid)
            {
                _context.Add(course);
                await _context.SaveChangesAsync();
                var newCourse = _context.Course.OrderBy(c => c.Id).Last();

                foreach (var presence in presences)
                {
                    presence.CourseId = newCourse.Id;
                    presence.Id = 0;
                    presence.Time = newCourse.Time;
                    presence.Active = false;
                    _context.Add(presence);
                }

                _context.SaveChanges();
                return RedirectToAction(nameof(Index),new {id = userId});
            }
           // ViewData["SubjectId"] = new SelectList(_context.Subject, "Id", "Name");
           // ViewData["LecturerId"] = new SelectList(_context.User.Where(u => u.RoleId == 2), "Id", "FullName");
            return View(course);
        }
        // GET: Courses/Edit/5
        [Authorize(Roles = "Lecturer,Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var courseDbContext =  await  _context.Course
                .Include(c => c.Subject)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (courseDbContext == null)
            {
                return NotFound();
            }
            ViewData["LecturerId"] = new SelectList(_context.User.Where(u => u.RoleId == 2), "Id", "FullName");
            return View(courseDbContext);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost,ActionName("Edit")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Lecturer,Admin")]
        public async Task<IActionResult> EditPost(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }
            

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var courseToUpdate = await _context.Course.FirstOrDefaultAsync(c => c.Id == id);
            
            if (await TryUpdateModelAsync<Course>(
                courseToUpdate,
                "",
                c => c.LecturerId,
                c => c.Time,
                c => c.Venue,
                c => c.Active
            ))
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!_context.Course.Any(e => e.Id == id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }

                    return RedirectToAction(nameof(Index),new {id = userId});
                }
            }

            ViewData["SubjectID"] = new SelectList(_context.Subject, "Id", "Id", courseToUpdate.Subject);
            return View(courseToUpdate);
        }

        // GET: Courses/Delete/5
        [Authorize(Roles = "Lecturer,Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.FileProviders;
using VDiary.Data;
using VDiary.Models;

namespace VDiary.Controllers
{
    [Authorize(Roles = "Admin,Lecturer")]
    public class SubjectsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SubjectsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Subjects
        public async Task<IActionResult> Index()
        {
            return View(await _context.Subject.ToListAsync());
        }

        // GET: Subjects/Create
        public IActionResult Create()
        {
           
            ViewData["Reffer"] = Request.Headers["Referer"].ToString();
            return View();
        }

        // POST: Subjects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name")] Subject subject,string? url)
        {
            if (ModelState.IsValid)
            {
                _context.Add(subject);
                await _context.SaveChangesAsync();
                if (url is not null)
                {
                    return Redirect(url);
                }

                return RedirectToAction(nameof(Index));
            }

            return View(subject);
        }

        // GET: Subjects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subject.FindAsync(id);
            if (subject == null)
            {
                return NotFound();
            }
            return View(subject);
        }

        // POST: Subjects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            var subjectToUpdate = await _context.Subject.FirstOrDefaultAsync(s => s.Id == id);
            if (await TryUpdateModelAsync<Subject>(
                subjectToUpdate,
                "",
                s => s.Name
            ))
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!_context.Subject.Any(e => e.Id == subjectToUpdate.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }

                    return RedirectToAction(nameof(Index));
                }
            }

            return View(subjectToUpdate);
        }

        // GET: Subjects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subject
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // POST: Subjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var subject = await _context.Subject.FindAsync(id);
            _context.Subject.Remove(subject);
            await _context.SaveChangesAsync();

            var relations = _context.SubjectUser.Where(su => su.SubjectId == id);
            foreach (var relation in relations)
            {
                _context.SubjectUser.Remove(relation);
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var su = _context.SubjectUser
                .Include(su => su.User)
                .Include(su => su.Subject)
                .Where(su => su.BelongsTo == su.UserId)
                .Where(su => su.SubjectId == id )
                .Select(su => su.User)
                ;

            ViewData["Subject"] = _context.Subject.Find(id);

            if (su == null)
            {
                return NotFound();
            }

            return View(su);
        }
    }
}

Views/Courses/AddStudent.cshtml
@using System.Security.Claims
@using System.Linq
@model IEnumerable<VDiary.Models.User>

@{
    ViewData["Title"] = "Edit";
    ViewData["filter"] = "";
    var student = new User();
}

<div class="row">
    <div class="col-sm-4">
        <form asp-action="AddStudent" asp-route-userId ="" asp-route-courseId="@ViewBag.CourseId" asp-route-subjectId="@ViewBag.subjectId">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label for="courseId" class="control-label">FullName</label>
                <select id="ddlStudents" class="form-control" asp-for="@Model.First().Id" value="@ViewBag.Students" asp-items="@ViewBag.Students" ></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>
                <td>
                    <form asp-controller="Courses" asp-action="AddStudent" asp-route-userId="@item.Id" asp-route-subjectId="@ViewData["SubjectId"]" asp-route-courseId="@ViewData["CourseId"]">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <input type="submit" value="Add User" class="btn btn-primary" />
                        </div>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    <a asp-action="ShowMembers" asp-route-subjectId="@ViewData["SubjectId"]" asp-route-courseId="@ViewData["CourseId"]" asp-route-lecturerId="@ViewData["lecturerId"]">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" />
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#ddlStudents").select2();
        });
    </script>
}

Views/Courses/Create.cshtml
@using System.Security.Claims
@model VDiary.Models.Course

@{
    ViewData["Title"] = "Create";
    var userId = "";
    var userRole = "";
    

    @if (User.Identity.IsAuthenticated)
    {
        userId = @User.FindFirst(c => c.Type == ClaimTypes.NameIdentifier).Value;
        userRole = @User.FindFirst(c => c.Type == ClaimTypes.Role).Value;
    }
}

<h1>Create</h1>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" >
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SubjectId" class="control-label"></label>
                <select asp-for="SubjectId" class="form-control" asp-items="ViewBag.SubjectId"></select>
                <div>
                    <a class="nav-link text-dark" asp-area="" asp-controller="Subjects" asp-action="Create">Add new Subject</a>
                </div>
            </div>
            @if (userRole != "Lecturer")
            {
                <div class="form-group">
                    <label asp-for="LecturerId" class="control-label"></label>
                    <select asp-for="LecturerId" class="form-control" asp-items="ViewBag.LecturerId"></select>
                    <span asp-validation-for="LecturerId" class="text-danger"></span>
                </div>
            }
            else
            {
                <div class="form-group">
                    @*<label asp-for="LecturerId" class="control-label">@Html.DisplayNameFor(model => model.LecturerId)</label>*@
                    <input type="hidden" asp-for="LecturerId" value="@userId"  class="form-control">
                    <span asp-validation-for="LecturerId" class="text-danger"></span>
                </div>
            }
            <div class="form-group">
                <label asp-for="Time" class="control-label"></label>
                <input asp-for="Time" class="form-control" />
                <span asp-validation-for="Time" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Venue" class="control-label"></label>
                <input asp-for="Venue" class="form-control" />
                <span asp-validation-for="Venue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupName" class="control-label"></label>
                <input asp-for="GroupName" class="form-control" />
                <span asp-validation-for="GroupName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-id="@userId">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Courses/CreateNewDate.cshtml
@model VDiary.Models.Course

@{
    ViewData["Title"] = "CreateNewDate";
    var error = TempData["Error"] as string;
}

<h1>Create new date</h1>

<h4>Course</h4>
<hr />
@if (!string.IsNullOrEmpty(error))
{
    <h1 class="alert-danger">@error</h1>
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateNewDate"  asp-route-id="@Model.Id">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Time" class="control-label"></label>
                <input asp-for="Time" class="form-control" />
                <span asp-validation-for="Time" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Courses/Delete.cshtml
@using System.Security.Claims
@model VDiary.Models.Course

@{
    ViewData["Title"] = "Delete";
    var userId="";
    @if (User.Identity.IsAuthenticated)
    {
        userId = @User.FindFirst(c => c.Type == ClaimTypes.NameIdentifier).Value;
    }

}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Subject.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LecturerId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LecturerId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Time)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Time)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Venue)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Venue)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.GroupName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GroupName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" asp-route-id="@userId">Back to List</a>
    </form>
</div>

Views/Courses/Details.cshtml
@model VDiary.Models.Course

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LecturerId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LecturerId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Time)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Time)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Venue)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Venue)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GroupName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GroupName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>|
    <a asp-action="CreateNewDate" asp-route-id="@Model.Id">Add new date</a>
</div>

Views/Courses/Edit.cshtml
@using System.Linq
@model VDiary.Models.Course

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="GroupName" />
            <input type="hidden" asp-for="SubjectId" />
            <input type="hidden" asp-for="Subject" />
            <div class="form-group">
                <label asp-for="LecturerId" class="control-label"></label>
                <select asp-for="LecturerId" class="form-control" asp-items="ViewBag.LecturerId"></select>
                <span asp-validation-for="LecturerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Time" class="control-label"></label>
                <input asp-for="Time" class="form-control" />
                <span asp-validation-for="Time" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Venue" class="control-label"></label>
                <input asp-for="Venue" class="form-control" />
                <span asp-validation-for="Venue" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Courses/Index.cshtml
@model IEnumerable<VDiary.Models.Course>
@using System.Security.Claims

@{
    ViewData["Title"] = "Index";
    var userId="";
    var userRole="";
    @if (User.Identity.IsAuthenticated)
    {
        userId = @User.FindFirst(c => c.Type == ClaimTypes.NameIdentifier).Value;
        userRole = @User.FindFirst(c => c.Type == ClaimTypes.Role).Value;
    }
}

<h1>All your courses </h1>
@if(userRole != "Student")
{
<p>
    <a asp-action="Create">Create New</a>
</p>
}
<table class="table">
    <thead>
        <tr>
            <th>
                Subject
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lecturer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Time)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Venue)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GroupName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Active)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Subject.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Lecturer.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Time)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Venue)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GroupName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Active)
                </td>
                <td>
                    @if (userRole != "Student")
                    {
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a><a> | </a>
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a><a> | </a>
                        <a asp-action="ShowMembers" asp-route-courseId="@item.Id" asp-route-subjectId="@item.SubjectId" asp-route-lecturerId="@item.LecturerId">Show members</a><a> | </a>
                        @if (userRole == "Lecturer")
                        {
                            <a asp-controller="Grades" asp-action="Create" asp-route-id="@item.SubjectId">Add grade</a><a> | </a>
                            <a asp-controller="Presences" asp-action="PresencesForCourse" asp-route-subjectId="@item.SubjectId" asp-route-courseId="@item.Id">Check Presences</a><a> | </a>
                        }
                    }
                    @if (userRole != "Lecturer")
                    {
                        <a asp-controller="Presences" asp-action="PresencesForSubject" asp-route-subjectId="@item.SubjectId" asp-route-lecturerId="@item.Lecturer.Id">Show presences</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

@{
    var prevDisabled = !ViewBag.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !ViewBag.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(ViewBag.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(ViewBag.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>