Controllers/GradesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VDiary.Data;
using VDiary.Models;
using VDiary.Models.Dtos;

namespace VDiary.Controllers
{
    [Authorize]
    public class GradesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public GradesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Grades/IndexForLecturer/1
        public async Task<IActionResult> IndexForLecturer(int? pageNumber)
        {
            var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var pageSize = 5;

            var applicationDbContext = await _context.SubjectUser
                    .Where(g => g.BelongsTo == userId )
                .Select(su => su.Subject)
                .Distinct()
                .ToListAsync()
                ;
            ViewData["lecturerId"] = userId;
            ;
            var grades = new PaginatedList<Subject>(applicationDbContext, applicationDbContext.Count, pageNumber ?? 1, pageSize);
            ViewData["HasPreviousPage"] = grades.HasPreviousPage;
            ViewData["HasNextPage"] = grades.HasNextPage;
            ViewData["PageIndex"] = grades.PageIndex;
            return View(await PaginatedList<Subject>.Create(grades, pageNumber ?? 1, pageSize));
        }
        // GET: Grades/IndexForStudent/1
        [Authorize(Roles = "Student")]
        public async Task<IActionResult> IndexForStudent(int? pageNumber)
        {
            var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            ViewData["userFullName"] = User.FindFirstValue(ClaimTypes.Name);


            var pageSize = 5;

            var applicationDbContext = _context.Grade
                .Include(m => m.Subject)
                .Include(m => m.User)
                .Where( m => m.UserId == userId )
                .Distinct()
                .AsEnumerable()
                .ToList()
                ;

            ViewData["Subjects"] = await _context.SubjectUser
                .Include(su => su.User)
                .Include(su => su.Subject)
                .Where(su => su.UserId == userId)
                .Distinct()
                .Select(su => su.Subject)
                .ToListAsync();

            var grades = new PaginatedList<Grade>(applicationDbContext, applicationDbContext.Count, pageNumber ?? 1, pageSize);
            ViewData["HasPreviousPage"] = grades.HasPreviousPage;
            ViewData["HasNextPage"] = grades.HasNextPage;
            ViewData["PageIndex"] = grades.PageIndex;
            return View(await PaginatedList<Grade>.Create(grades, pageNumber ?? 1, pageSize));
        }

        public async Task<IActionResult> AllGradesOfStudent(int studentId,int subjectId)
        {

            if (studentId == 0 || studentId == null)
            {
                return NotFound();
            }

            var results = await _context.Grade
                .Include(g => g.User)
                .Where(g => g.UserId == studentId)
                .Where(g => g.SubjectId == subjectId)
                .ToListAsync();
            
            ViewData["UserName"] = _context.User.SingleOrDefault( u => u.Id == studentId);
            ViewData["SubjectId"] = subjectId;


            return View(results);
        }

        // GET: Marks/Create
        [Authorize(Roles = "Lecturer")]
        public IActionResult CreateDefault()
        {

            var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var subjects =  _context.Course
                .Where(c => c.LecturerId == userId)
                .Select(c => c.Subject)
                ;

            var students = _context.SubjectUser
                .Where(su => su.BelongsTo == userId)
                .Where(su => su.User.Role.Name == "Student")
                .Select(su => su.User);

            ViewData["SubjectId"] = new SelectList(subjects, "Id", "Name");
            ViewData["UserId"] = new SelectList(students, "Id", "FullName");
            return View();
        }
        // GET: Marks/Create/1
        [Authorize(Roles = "Lecturer")]
        public IActionResult Create(int? id)// subjectID,
        {
            if (id is null)
            {
                return RedirectToAction("CreateDefault");
            }
            var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var subject =  _context.Subject
                .FirstOrDefault(s => s.Id == id );

            var students = _context.SubjectUser
                .Where(su => su.BelongsTo == userId)
                .Where(su => su.User.Role.Name == "Student")
                .Where(s => s.Subject ==  subject)
                .Select(su => su.User);

            ViewData["SubjectId"] = subject.Id;
            ViewData["UserId"] = new SelectList(students, "Id", "FullName");
            return View();
        }

        // POST: Marks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Lecturer")]
        public async Task<IActionResult> Create([Bind("GradeMark,Date,Description,UserId,SubjectId,CreatedBy")] Grade grade)
        {
            var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            grade.CreatedBy = userId;
            if (ModelState.IsValid)
            {
                _context.Add(grade);
                await _context.SaveChangesAsync();
                return RedirectToAction("AllGradeForSubject",new{ id = grade.SubjectId});
            }
            ViewData["SubjectId"] = new SelectList(_context.Subject, "Id", "Name", grade.SubjectId);
            ViewData["UserId"] = new SelectList(_context.User, "Id", "AlbumNumber", grade.UserId);
            return View(grade);
        }

        // GET: Marks/Edit/5
        [Authorize(Roles = "Lecturer")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mark = await _context.Grade.FindAsync(id);
            if (mark == null)
            {
                return NotFound();
            }
            ViewData["SubjectId"] = new SelectList(_context.Subject, "Id", "Name", mark.SubjectId);
            ViewData["UserId"] = new SelectList(_context.User, "Id", "AlbumNumber", mark.UserId);
            return View(mark);
        }

        // POST: Marks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Lecturer")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,GradeMark,Date,Description,UserId,SubjectId,CreatedBy")] Grade grade)
        {
            if (id != grade.Id)
            {
                return NotFound();
            }

            var subjectId = grade.SubjectId;
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(grade);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Grade.Any(e => e.Id == grade.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(AllGradeForSubject), new { id = subjectId });
            }
            ViewData["SubjectId"] = new SelectList(_context.Subject, "Id", "Name", grade.SubjectId);
            ViewData["UserId"] = new SelectList(_context.User, "Id", "AlbumNumber", grade.UserId);
            return View();
        }

        // GET: Marks/Delete/5
        [Authorize(Roles = "Lecturer")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mark = await _context.Grade
                .Include(m => m.Subject)
                .Include(m => m.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (mark == null)
            {
                return NotFound();
            }

            return View(mark);
        }

        // POST: Marks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mark = await _context.Grade.FindAsync(id);
            _context.Grade.Remove(mark);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(IndexForLecturer));
        }

        public async Task<IActionResult> AllGradeForSubject(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }
            var lecturerId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var subject = _context.Subject.FirstOrDefault(s => s.Id == id);
            var grades = await _context.Grade
                .Include(g => g.Subject)
                .Include(g => g.User)
                .Where(g => g.SubjectId == id)
                .Where(g => g.CreatedBy == lecturerId)
                .ToListAsync();

            ViewData["Subject"] = subject;

            ViewData["Students"]= await _context.User

Controllers/PresencesController.cs
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using VDiary.Data;
using VDiary.Models;

namespace VDiary.Controllers
{
    [Authorize]
    public class PresencesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PresencesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Presences
        [Authorize(Roles = "Lecturer")]
        public async Task<IActionResult> AllPresencesOfStudent(int studentId, int subjectId)
        {

            if (studentId == null)
            {
                return NotFound();
            }

            var results =  await _context.Presence
                .Include(p => p.User)
                .Include(p => p.Course)
                .Where(p => p.UserId == studentId)
                .Where(p => p.Course.SubjectId == subjectId)
                .ToListAsync()
                
                ;

            return View(results);
        }

        // GET: Presences/Create
        [Authorize(Roles = "Lecturer")]

        public IActionResult CheckPresence(int? courseId, int? subjectId)
        {
            if (subjectId == null)
            {
                return NotFound();
            }

            var presences = _context.Presence
                    .Include(p => p.User)
                    .Where(p => p.CourseId == courseId)
                    .ToList()
                ;


            return View(presences);
        }

        // POST: Presences/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Lecturer")]
        public async Task<IActionResult> CheckPresence([Bind("Id,CourseId,UserId,Active,Course,User")] List<Presence> presences)
        {

            if (ModelState.IsValid)
            {
                foreach (var presence in presences)
                {
                    _context.Update(presence);

                }
                await _context.SaveChangesAsync();
                var course = _context.Course
                    .First(c => c.Id == presences.FirstOrDefault().CourseId)

                    ;

                return RedirectToAction("PresencesForCourse", new
                {
                    courseId = course.Id,
                    subjectId = course.SubjectId
                });
            }
            return View(presences);
        }

        // GET: Presences/Edit/5
        [Authorize(Roles = "Lecturer")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var presence = await _context.Presence
                .FindAsync(id);
            if (presence == null)
            {
                return NotFound();
            }
            return View(presence);
        }

        // POST: Presences/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Lecturer")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CourseId,UserId,Active")] Presence presence)
        {
            if (id != presence.Id)
            {
                return NotFound();
            }

            var contextDb = _context.Course
                .SingleOrDefaultAsync(p => p.Id == presence.CourseId);

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(presence);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.Presence.Any(e => e.Id == presence.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(AllPresencesOfStudent),new {studentId = presence.UserId, subjectId = contextDb.Result.SubjectId});
            }
            return View(presence);
        }

        public async Task<IActionResult> PresencesForCourse(int? courseId , int? subjectId)
        {
            if (courseId is null)
            {
                return NotFound();
            }
            var lecturerId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var subject = _context.Subject.FirstOrDefault(s => s.Id == subjectId);
            var presences = await _context.Presence
                    .Include(p => p.Course)
                    .Include(p => p.User)
                    .Where(p => p.CourseId == courseId)
                    .ToListAsync()
                    ;

            ViewData["Subject"] = subject;
            ViewData["CourseId"] = courseId;

            ViewData["Students"] = _context.User
                    .Include(u => u.SubjectUser)
                    .Where(u => u.SubjectUser.FirstOrDefault(su => su.BelongsTo == lecturerId).BelongsTo == lecturerId)
                    .Where(u => u.SubjectUser.FirstOrDefault(su => su.Subject.Name == subject.Name).Subject.Name == subject.Name)
                    .Where(u => u.Role.Name == "Student")
                ;

            return View(presences);
        }

        public IActionResult PresencesForSubject( int? subjectId,int? lecturerId)
        {
            var presents = _context.Presence
                .Include(p => p.Course)
                .Include(p => p.User)
                .Include(p => p.Course.Subject)
                .Where(p => p.Course.SubjectId == subjectId)
                .OrderBy(p => p.Time)
                ;
            ViewData["Lecturer"] = _context.User.FirstOrDefault( c => c.Id == lecturerId);
            var userRole = User.FindFirstValue(ClaimTypes.Role);
            ViewData["Subject"] = _context.Subject.FirstOrDefault(s => s.Id== subjectId);
            if (userRole == "Student")
            {
                var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
                presents = presents.Where(p => p.UserId == userId)
                    .OrderBy(p => p.Time);
                return View(presents);
            }
            return View(presents);
        }

        [Authorize(Roles = "Student")]
        public async Task<IActionResult> PresencesForStudent(int? pageNumber)
        {
            var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            ViewData["userFullName"] = User.FindFirstValue(ClaimTypes.Name);


            var pageSize = 5;

            if (pageNumber is null)
            {
                pageNumber = 1;
            }
            var applicationDbContext = _context.SubjectUser
                    .Include(m => m.Subject)
                    .Include(m => m.User)
                    .Where(m => m.UserId == userId)
                    .AsEnumerable()
                    .ToList()
                ;
            var su = new PaginatedList<SubjectUser>(applicationDbContext, applicationDbContext.Count, pageNumber ?? 1, pageSize);
            ViewData["HasPeireviousPage"] = su.HasPreviousPage;
            ViewData["HasNextPage"] = su.HasNextPage;
            ViewData["PageIndex"] = su.PageIndex;
            return View(await PaginatedList<SubjectUser>.Create(su, pageNumber ?? 1, pageSize));
        }
    }
}

Views/Presences/AllPresencesOfStudent.cshtml
@model IEnumerable<VDiary.Models.Presence>

@{
    ViewData["Title"] = "AllPresencesOfStudent";
}

<h1>All presences of @Model.FirstOrDefault().User.FullName</h1>

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active)
        </th>

        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Active)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
            </td>
        </tr>
    }
    </tbody>
</table>

<a asp-action="PresencesForSubject" asp-route-subjectId="@Model.FirstOrDefault().Course.SubjectId">Back </a>

Views/Presences/CheckPresence.cshtml
@*@model VDiary.Models.Presence*@
@using System.Linq
@model List<VDiary.Models.Presence>
@{
    ViewData["Title"] = "Create";
    var course = Model[0].Course;
}

<h1>Create</h1>

<h4>Presence</h4>
<hr />
<div class="row">
    <div class="col-md-4">
    
        <form asp-action="CheckPresence">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model[0].User.FullName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model[0].Active)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @for (int row = 0 ; row < Model.Count(); row++)
                    {
                        @Html.HiddenFor(item => item[row].UserId)
                        @Html.HiddenFor(item => item[row].CourseId)
                        @Html.HiddenFor(item => item[row].Id)
                        @Html.HiddenFor(item => item[row].Time @*, new { Value = time}*@)
                        <tr>
                            <td>
                                @Html.DisplayFor(item => item[row].User.FullName)
                            </td>
                            <td >
                                @Html.EditorFor(item => item[row].Active)
                            </td>
                        </tr>
                    }

                </tbody>
                
            </table>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    
    
    </div>
</div>

<div>
    @*<a asp-action="PresencesForCourse" asp-route-courseId ="@course.Id" asp-route-subjectId="@course.SubjectId">Back to List</a>*@
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Presences/Create.cshtml
@*@model VDiary.Models.Presence*@
@using System.Linq
@model List<VDiary.Models.Presence>
@{
    ViewData["Title"] = "Create";
    var course = Model[0].Course;
}

<h1>Create</h1>

<h4>Presence</h4>
<hr />
<div class="row">
    <div class="col-md-4">
    
        <form asp-action="Create">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model[0].User.FullName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model[0].Active)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @for (int row = 0 ; row < Model.Count(); row++)
                    {
                        @Html.HiddenFor(item => item[row].UserId)
                        @Html.HiddenFor(item => item[row].CourseId)
                        @Html.HiddenFor(item => item[row].Id)
                        @Html.HiddenFor(item => item[row].Time @*, new { Value = time}*@)
                        <tr>
                            <td>
                                @Html.DisplayFor(item => item[row].User.FullName)
                            </td>
                            <td >
                                @Html.EditorFor(item => item[row].Active)
                            </td>
                        </tr>
                        @*<tr>
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <input type="hidden" asp-for="@Model[row]" class="form-control" asp-items="@item.CourseUserId">
                            </div>

                            <td>

                                <div class="form-group form-check">
                                    <label class="form-check-label">
                                        @item.CourseUser.User.FullName <input class="form-check-input" asp-for="@item.Active" />
                                    </label>
                                </div>
                            </td>
                            <div class="form-group form-check">
                                <label class="form-check-label">

                                </label>
                            </div>
                        </tr>
                        <div class="form-group">
                    <label asp-for="Time" class="control-label"></label>
                    <input asp-for="Time" class="form-control" />
                    <span asp-validation-for="Time" class="text-danger"></span>
                </div>*@
                    }

                </tbody>
                
            </table>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    
    
    </div>
</div>

<div>
    <a asp-action="PresencesForCourse" asp-route-courseId ="@course.Id" asp-route-subjectId="@course.SubjectId">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Presences/Edit.cshtml
@model VDiary.Models.Presence

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Presence</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Time" class="control-label"></label>
                <input asp-for="Time" class="form-control" />
                <span asp-validation-for="Time" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input asp-for="CourseId" type="hidden" />
            </div>
            <div class="form-group">
                <input asp-for="UserId" type="hidden" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Presences/PresencesForCourse.cshtml
@using Microsoft.EntityFrameworkCore
@model IEnumerable<VDiary.Models.Presence>


@{
    ViewData["Title"] = "IndexForLecturer";
    var students = ViewBag.Students;
    var subject = ViewBag.Subject;
    var courseId = ViewBag.CourseId;
}

<h1>These are all presences from  @subject.Name  on @Model.FirstOrDefault().Time </h1>
<a asp-controller="Grades" asp-action="Create" asp-route-id="@subject.Id">Add grade</a>


<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.User.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active)
        </th>
        <th></th>
        
    </tr>
    </thead>
    <tbody>
    @foreach (var presence in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => presence.User.FullName)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => presence.Active)
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    <a asp-controller="Courses" asp-action="Index" asp-route-id="@subject.Id">Back to List</a>
</div>
<div>
    <a asp-action="CheckPresence" asp-route-courseId="@courseId" asp-route-subjectId="@subject.Id" asp-route-lecturerId="">Check presence</a>
</div>

Views/Presences/PresencesForStudent.cshtml
@model IEnumerable<VDiary.Models.SubjectUser>

@{
    ViewData["Title"] = "IndexForLecturer";
}

<h1>Hello @ViewBag.userFullName these are your presences </h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Subject)
            </th>
            <th>
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Subject.Name)
                </td>
                <td>
                    <a asp-controller="Presences" asp-action="PresencesForSubject" asp-route-subjectId="@item.SubjectId" asp-route-lecturerId="@item.BelongsTo">Show presence</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@{
    var prevDisabled = !ViewBag.HasPeireviousPage ? "disabled" : "";
    var nextDisabled = !ViewBag.HasNextPage ? "disabled" : "";
}

<a asp-action="PresencesForSubject"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(ViewBag.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="PresencesForSubject"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(ViewBag.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>

Views/Presences/presencesForSubject.cshtml
@model IEnumerable<VDiary.Models.Presence>
@using System.Security.Claims



@{
    ViewData["Title"] = "IndexForLecturer";
    var userRole = @User.FindFirst(c => c.Type == ClaimTypes.Role).Value;
    var subjectid = @ViewBag.Subject.Id;
}

<h1>These are all presences from  @ViewBag.Subject.Name witch @ViewBag.Lecturer.FullName</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.User.FullName)
            </th>
            @foreach (var date in Model.GroupBy(item => item.Time).Distinct())
            {
                <th>
                    @Html.DisplayFor(modelItem => date.Key)
                </th>
            }
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var group in Model.GroupBy(item => item.User.FullName))
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => group.Key)
                </td>
                @foreach (var item in group)
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.Active)
                    </td>
                }
                @if (userRole == "Lecturer")
                {
                <td><a asp-action="AllPresencesOfStudent" asp-route-studentId="@group.FirstOrDefault().UserId" asp-route-subjectId="@subjectid">Edit</a></td>
                }
            </tr>
        }

    </tbody>
</table>

<div>
    <a href="javascript:history.go(-1)">Back to List</a>
</div>